### ISSUE TITLE
TS support missing from npm

### ISSUE THREAD

**Issue by innermatrix** [Coggle/friendly-truncate#3]
Sorry to bug you again — it looks like my patch to add TS support from #1 made it into the tree, but not into npm: https://www.npmjs.com/package/friendly-truncate/v/1.2.0?activeTab=code. I am not sure what build script you are using do generate the npm dist, or else I'd drop you a patch for it…  Thanks!

**Comment by autopulated** [comment]
Sorry! this was because I missed updating `files:` in package.json.

Fixed in 1.3.0 published just now
